replicaCount: 1

image:
  repository: <dockerhub-user>/<image-name>
  tag: <tag>
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpu:
    targetAverageUtilization: 50
  memory:
    targetAverageUtilization: 60

keda:
  trigger:
    type: kafka
    metadata:
      bootstrapServers: <kafka-bootstrap>
      topic: <topic-name>
      consumerGroup: <consumer-group>
      lagThreshold: "10"
