apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-autoscaler-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dhanush2021/Argoapp.git
    targetRevision: main
    path: charts/keda-autoscaler
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
